name: Run my python
on:
    push:
jobs:
    bulid:
        name: do job1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Send email
          run: |
            python3 send_mail.py
    bulid2:
        name: do job2
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run test2 py
          run: |
            python3 test2.py